@startuml 单例模式

class Singleton {
    - {static} instance: Singleton
    + getInstance(): Singleton
}

Singleton::getInstance *--> Singleton
@enduml


class Singleton {
    - {static} instance:Singleton = new Singleton()
    + getInstance(): Singleton
}

Singleton::getInstance *--> Singleton



class Singleton {
    - {static} instance:Singleton
    + getInstance(): Singleton
}
note left of Singleton::"getInstance()"
    if(instance == null) {
        instance = new LazySingleton();
    }
end note
Singleton::getInstance *--> Singleton

