## 单例模式
```uml
class Singleton {
    - {static} instance: Singleton
    + getInstance(): Singleton
}

Singleton::getInstance *--> Singleton
```

```uml
class Singleton {
    - {static} instance:Singleton = new Singleton()
    + getInstance(): Singleton
}

Singleton::getInstance *--> Singleton
```

```uml
class Singleton {
    - {static} instance:Singleton
    + getInstance(): Singleton
}
note left of Singleton::"getInstance()"
    if(instance == null) {
        instance = new LazySingleton();
    }
end note
Singleton::getInstance *--> Singleton
```
