name: Deploy

on:
  push:
    branches: [main, dev]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          ls
          chmod +x scripts/plantuml.jar
          sudo apt-get install plantuml -y
          sudo apt-get install graphviz -y
          pip install -r requirements.txt

      - name: build doc
        run: make html

      - name: copy html
        run: touch build/html/.nojekyll

      - name: fix comments
        run: python scripts/fix-comments.py

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
